import { test, expect } from '@playwright/test'
import { validBackup, validStored } from '../src/validation'
test('reject malformed backups and stored state', () => {
 expect(validBackup({ app: 'wo-logger', version: 1, history: [{}] })).toBe(false)
 expect(validStored('settings', {unit: 'stone', defaultRestSec: 90})).toBe(false)
 expect(validStored('settings', {unit: 'lb', defaultRestSec: 90})).toBe(true)
 expect(validStored('history', [{id: 'bad', entries: null}])).toBe(false)
})
test('record workout, persist history and use keyboard dialog', async ({ page }) => {
 const errors: string[] = []
 page.on('pageerror', e => errors.push(e.message))
 await page.goto('./')
 await page.getByRole('button', { name: 'Start training' }).click()
 await page.getByRole('button', { name: '+ Start empty workout', exact: true }).click()
 await page.getByRole('button', { name: '+ Add exercises', exact: true }).click()
 await page.getByPlaceholder('Search exercises…').fill('Bench Press')
 await page.locator('.picker-item').first().click()
 await page.getByRole('button', { name: "Add (1)" }).click()
 await page.locator('.num-input').nth(0).fill('60')
 await page.locator('.num-input').nth(1).fill('8')
 await page.getByTitle('Mark set complete').click()
 await page.getByRole('button', {name: 'Finish', exact: true}).click()
 await expect(page.getByRole('dialog')).toContainText('Workout complete')
 await page.getByRole('button', { name: 'Done', exact: true }).click()
 await expect(page.locator('.workout-card')).toContainText('480 kg')
 await page.reload()
 await page.getByRole('button', {name: 'History', exact: false}).click()
 await expect(page.locator('.workout-card')).toHaveCount(1)
 await page.locator('.workout-card').click()
 await expect(page.getByRole('dialog')).toBeVisible()
 await page.keyboard.press('Escape')
 await expect(page.getByRole('dialog')).toHaveCount(0)
 expect(errors).toEqual([])
 await page.setViewportSize({width: 390, height: 844})
 expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})
